/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/retro": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["RetroListItem"][];
                        "application/json": components["schemas"]["RetroListItem"][];
                        "text/json": components["schemas"]["RetroListItem"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateRetroRequest"];
                    "text/json": components["schemas"]["CreateRetroRequest"];
                    "application/*+json": components["schemas"]["CreateRetroRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CreateRetroResponse"];
                        "application/json": components["schemas"]["CreateRetroResponse"];
                        "text/json": components["schemas"]["CreateRetroResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/retro/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["GetRetroResponse"];
                        "application/json": components["schemas"]["GetRetroResponse"];
                        "text/json": components["schemas"]["GetRetroResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/retro/{id}/finish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/retro/{id}/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateRetroSettingsRequest"];
                    "text/json": components["schemas"]["UpdateRetroSettingsRequest"];
                    "application/*+json": components["schemas"]["UpdateRetroSettingsRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/retro/{id}/phase/next": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SetRetroPhaseRequest"];
                    "text/json": components["schemas"]["SetRetroPhaseRequest"];
                    "application/*+json": components["schemas"]["SetRetroPhaseRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/retro/{id}/phase/back": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SetRetroPhaseRequest"];
                    "text/json": components["schemas"]["SetRetroPhaseRequest"];
                    "application/*+json": components["schemas"]["SetRetroPhaseRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/retro/{id}/timer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SetRetroTimerRequest"];
                    "text/json": components["schemas"]["SetRetroTimerRequest"];
                    "application/*+json": components["schemas"]["SetRetroTimerRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/retro/{id}/discussed-card": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SetRetroDiscussedCardRequest"];
                    "text/json": components["schemas"]["SetRetroDiscussedCardRequest"];
                    "application/*+json": components["schemas"]["SetRetroDiscussedCardRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/retro/{id}/reveal-mine": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SetRetroRevealRequest"];
                    "text/json": components["schemas"]["SetRetroRevealRequest"];
                    "application/*+json": components["schemas"]["SetRetroRevealRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/retro/{id}/cards": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateRetroCardRequest"];
                    "text/json": components["schemas"]["CreateRetroCardRequest"];
                    "application/*+json": components["schemas"]["CreateRetroCardRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CreateRetroCardResponse"];
                        "application/json": components["schemas"]["CreateRetroCardResponse"];
                        "text/json": components["schemas"]["CreateRetroCardResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/retro/cards/{cardId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    cardId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateRetroCardRequest"];
                    "text/json": components["schemas"]["UpdateRetroCardRequest"];
                    "application/*+json": components["schemas"]["UpdateRetroCardRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    cardId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/retro/cards/{cardId}/position": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    cardId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["MoveRetroCardRequest"];
                    "text/json": components["schemas"]["MoveRetroCardRequest"];
                    "application/*+json": components["schemas"]["MoveRetroCardRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/retro/cards/{cardId}/vote": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    cardId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SetRetroCardVoteRequest"];
                    "text/json": components["schemas"]["SetRetroCardVoteRequest"];
                    "application/*+json": components["schemas"]["SetRetroCardVoteRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/retro/cards/{cardId}/done": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    cardId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SetRetroCardDoneRequest"];
                    "text/json": components["schemas"]["SetRetroCardDoneRequest"];
                    "application/*+json": components["schemas"]["SetRetroCardDoneRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/retro/{id}/groups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["GroupRetroCardsRequest"];
                    "text/json": components["schemas"]["GroupRetroCardsRequest"];
                    "application/*+json": components["schemas"]["GroupRetroCardsRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["GroupRetroCardsResponse"];
                        "application/json": components["schemas"]["GroupRetroCardsResponse"];
                        "text/json": components["schemas"]["GroupRetroCardsResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/retro/{id}/groups/{groupId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                    groupId: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SetRetroGroupTitleRequest"];
                    "text/json": components["schemas"]["SetRetroGroupTitleRequest"];
                    "application/*+json": components["schemas"]["SetRetroGroupTitleRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                    groupId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/retro/cards/{cardId}/assignee": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    cardId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SetRetroCardAssigneeRequest"];
                    "text/json": components["schemas"]["SetRetroCardAssigneeRequest"];
                    "application/*+json": components["schemas"]["SetRetroCardAssigneeRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/retro/cards/{cardId}/reveal": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    cardId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SetRetroCardRevealedRequest"];
                    "text/json": components["schemas"]["SetRetroCardRevealedRequest"];
                    "application/*+json": components["schemas"]["SetRetroCardRevealedRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CreateRetroCardRequest: {
            /** Format: int64 */
            sectionId: number | string;
            text: string;
            /** Format: double */
            x: number | string;
            /** Format: double */
            y: number | string;
        };
        CreateRetroCardResponse: {
            /** Format: uuid */
            id: string;
        };
        CreateRetroRequest: {
            name: string;
        };
        CreateRetroResponse: {
            /** Format: int64 */
            id: number | string;
        };
        GetRetroResponse: {
            /** Format: int64 */
            id: number | string;
            name: string;
            color: string;
            phase: components["schemas"]["RetroPhase"];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            finishedAt: null | string;
            /** Format: int32 */
            votesPerUser: number | string;
            /** Format: int32 */
            myVotes: number | string;
            /** Format: date-time */
            phaseEndsAt: null | string;
            /** Format: uuid */
            discussedCardId: null | string;
            canManage: boolean;
            owner: components["schemas"]["RetroUser"];
            currentUser: components["schemas"]["RetroUser"];
            participants: components["schemas"]["RetroUser"][];
            sections: components["schemas"]["RetroSectionDto"][];
            cards: components["schemas"]["RetroCardDto"][];
            groups: components["schemas"]["RetroCardGroupDto"][];
        };
        GroupRetroCardsRequest: {
            cardIds: string[];
        };
        GroupRetroCardsResponse: {
            /** Format: int64 */
            id: number | string;
        };
        MoveRetroCardRequest: {
            /** Format: int64 */
            sectionId: number | string;
            /** Format: double */
            x: number | string;
            /** Format: double */
            y: number | string;
        };
        RetroCardDto: {
            /** Format: uuid */
            id: string;
            /** Format: int64 */
            sectionId: number | string;
            text: string;
            /** Format: double */
            x: number | string;
            /** Format: double */
            y: number | string;
            /** Format: int32 */
            stackOrder: number | string;
            done: boolean;
            hidden: boolean;
            revealed: boolean;
            isMine: boolean;
            assignee: null | components["schemas"]["RetroUser"];
            /** Format: int64 */
            groupId: null | number | string;
            /** Format: int32 */
            votes: number | string;
            votedByMe: boolean;
            author: components["schemas"]["RetroUser"];
        };
        RetroCardGroupDto: {
            /** Format: int64 */
            id: number | string;
            title: string;
            cardIds: string[];
            /** Format: int32 */
            votes: number | string;
            votedByMe: boolean;
        };
        RetroListItem: {
            /** Format: int64 */
            id: number | string;
            name: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            finishedAt: null | string;
            /** Format: int32 */
            cardCount: number | string;
        };
        /** @enum {unknown} */
        RetroPhase: "Collect" | "Vote" | "Discuss" | "Group" | "Actions";
        RetroSectionDto: {
            /** Format: int64 */
            id: number | string;
            name: string;
            color: string;
            /** Format: int32 */
            sortOrder: number | string;
        };
        RetroUser: {
            /** Format: uuid */
            userId: string;
            displayName: string;
            initials: string;
            color: string;
            isCurrentUser: boolean;
        };
        SetRetroCardAssigneeRequest: {
            /** Format: uuid */
            assigneeId: null | string;
        };
        SetRetroCardDoneRequest: {
            done: boolean;
        };
        SetRetroCardRevealedRequest: {
            revealed: boolean;
        };
        SetRetroCardVoteRequest: {
            voted: boolean;
        };
        SetRetroDiscussedCardRequest: {
            /** Format: uuid */
            cardId: null | string;
        };
        SetRetroGroupTitleRequest: {
            title: string;
        };
        SetRetroPhaseRequest: {
            phase: components["schemas"]["RetroPhase"];
        };
        SetRetroRevealRequest: {
            revealed: boolean;
        };
        SetRetroTimerRequest: {
            /** Format: int32 */
            minutes: null | number | string;
        };
        UpdateRetroCardRequest: {
            text: string;
        };
        UpdateRetroSettingsRequest: {
            phase: components["schemas"]["RetroPhase"];
            /** Format: int32 */
            votesPerUser: number | string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
